/* Sample doc for the "Try the sample" button. A made-up business on example.com, written the way a strategist
   might: headings, a campaign table, bullet lists, a headline table and a few lines the tool should not import. */
(function (root) {
  'use strict';
  const SAMPLE_TEXT = [
    '# Harbor Plumbing – Google Search Campaign Plan',
    '',
    'Final URL: https://www.example.com/',
    'Locations: Austin, TX; Round Rock, TX (presence only)',
    'Bidding: Maximize conversions',
    '',
    '## Campaign structure',
    '| Campaign | Ad Groups | Monthly Budget |',
    '|---|---|---|',
    '| A - Urgent Repairs | Emergency Plumbing; Drain Cleaning | $1,520 |',
    '| B - Installs | Water Heater Installation | $912 |',
    '',
    '## Emergency Plumbing',
    '**Keywords**',
    '- emergency plumber',
    '- 24 hour plumber',
    '- [emergency plumber near me]',
    '- "burst pipe repair"',
    '**Headlines**',
    '| Headline | Chars |',
    '|---|---|',
    '| 24/7 Emergency Plumbers | 23 |',
    '| Fast Burst Pipe Repair | 22 |',
    '| Licensed Local Plumbers | 23 |',
    '| No Call-Out Surprises | 21 |',
    '| Plumber At Your Door Fast | 25 |',
    '**Descriptions**',
    '- Licensed plumbers on call day and night. Upfront pricing before any work starts.',
    '- Burst pipe or no hot water? Book a plumber and get a firm arrival time today.',
    'Final URL: https://www.example.com/emergency-plumber',
    '',
    '## Drain Cleaning',
    'Keywords: drain cleaning, blocked drain service, clogged drain plumber, drain unblocking',
    'Headline 1: Blocked Drain Specialists',
    'Headline 2: Same Day Drain Cleaning',
    'Headline 3: Clear Drains, Fair Prices',
    'Headline 4: Camera Drain Inspections',
    'Description 1: We clear kitchen, bathroom and main drains with camera checks to find the cause.',
    'Description 2: Same day drain cleaning from local plumbers. Upfront quote before we start.',
    '',
    '## Water Heater Installation',
    '**Keywords**',
    '- water heater installation',
    '- tankless water heater install',
    '- replace water heater',
    '**Ad copy**',
    '- Water Heater Installation',
    '- Tankless Heaters Installed',
    '- Hot Water Back Today',
    '- Gas, electric and tankless water heaters supplied and fitted by licensed plumbers.',
    '- Old heater failing? Get a fixed-price replacement quote with no hidden fees.',
    '',
    '## Negative keywords (all campaigns)',
    '- jobs',
    '- diy',
    '- [plumber salary]',
    '- free',
    '',
    '## Sitelinks',
    '- Book Online',
    '- Our Prices',
    '',
    '## Notes for the team',
    'Pin headline 1 to position 1 in Emergency Plumbing once the account has 30 days of data.'
  ].join('\n');
  root.CBSample = { name: 'Harbor_Plumbing_sample.md', text: SAMPLE_TEXT };
})(typeof window !== 'undefined' ? window : globalThis);
